# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Maskulin'), ('f', 'Feminin'), ('n', 'Neutrum'), ('p', 'Plural')], max_length=1)),
                ('details', models.TextField(blank=True)),
                ('latest_update', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='noun',
            unique_together=set([('word', 'gender')]),
        ),
    ]
